import { User } from "./userTypes";

export type Client = {
  id_account: number;
  created_at_account: string;
  pre_activation_consumption: number;
  vendor_account: string;
  company_name_account: string | null;
  fantasy_name_account: string | null;
  cnpj_cpf_account: string | null; 
  type_account: string | null;
  phase_account: string;
  status_account: "Ativo" | "Inativo" | "Pendente" | "Cadastrado";
  status_cnpj: 'Ativo' | 'Inapto';
  source_account: string;
  default_blocked: number;
  rank_account: string | null;
  billing_date_account: string | null;
  status_approved: string;
  date_approved: string | null;
  uf_inscription_account: string | null;
  street_account: string | null;
  number_account: string | null;
  complement_account: string | null;
  cep_account: string | null;
  city_account: string | null;
  uf_account: string;
  country_account: string | null;
  name_account: string;
  email_account: string;
  email_financeiro_account: string | null;
  email_logistica_account: string | null;
  phone_account: string;
  credit_limit_account: number | null;
  credit_balance_account: number | null;
  obs_account: string | null;
  obs_lead_account: string | null;
  phase_lead_account: string;
  reason_lead_account: string | null;
  lead_type_account: string;
  date_prospect_account: string | null;
  date_conquered_account: string | null;
  social_capital_account: string | null;
  wp_number_account: string | null;
  black_list_account: any;
  bloq_sms_account: string | null | any;
  import_account: string | null;
  customer_id_allgar: string | null;
  codigo_cliente_integracao: string | null;
  codigo_cliente_omie: string | null;
  codigo_rdstation: string | null;
  updated_at_account: string | null;
  strategic_client_account: string;
  fk_default_representante_legal: string
  email_omie_account: string
  ocupation_area: string;
  account_owner: string;
  is_canal: number;
  allmanager_account: string;
  campaign_account: string | null;
  district_account: string | null;
  shared_default_contract_algar: string;
  justification_discard: string;
  reason_discard: string;
  natureza_juridica: string;
  vendedores?: Pick<User, 'id_user' | 'name_user'>[];
};